name: moq.js

on:
    pull_request:
        branches: ["main"]

jobs:
    check:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v3

            - name: install
              run: pnpm install

            - name: build
              run: pnpm -r build

            - name: lint
              run: pnpm -r lint
