name: Release Docker Image

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

on:
    push:
        branches: ["main"]

jobs:
    build:
        runs-on: ubuntu-latest

        # Only one release at a time and cancel prior releases
        concurrency:
            group: release
            cancel-in-progress: true

        steps:
            - name: Checkout
              uses: actions/checkout@v3

            # I'm paying for Depot for faster ARM builds.
            - name: Setup depot
              uses: depot/setup-action@v1

            - name: Setup gcloud
              uses: google-github-actions/setup-gcloud@v0.6.0
              with:
                  project_id: quic-video
                  service_account_key: ${{ secrets.GCP_SERVICE_ACCOUNT_KEY }}

            - name: Configure docker for GCP
              run: gcloud auth configure-docker

            # Build and push Docker image with Depot
            - name: Build and push Docker image
              uses: depot/build-push-action@v1
              with:
                  project: hppp3x0qjc
                  context: .
                  push: true
                  tags: us-central1-docker.pkg.dev/quic-video/deploy/moq-js:latest
