# note: root .editorconfig is used

# Don't insert semi-colons unless needed
semi: false

plugins:
    - "prettier-plugin-tailwindcss"
    - "prettier-plugin-astro"

overrides:
    - files: "*.astro"
      options:
          parser: "astro"
